# SubTract Pipeline Configuration for HPC/Singularity
# Template configuration file for Docker/Singularity deployment
# Version: 1.0.0-alpha

# Paths configuration - these should be mounted volumes in the container
paths:
  base_path: /data                                    # Base directory (mount your data here)
  data_dir: /data/bids                               # BIDS dataset directory
  analysis_dir: /data/derivatives/subtract           # Analysis outputs directory
  result_dir: /data/derivatives/subtract/results     # Final results directory
  script_dir: /opt/subtract/src                      # Scripts directory (in container)

# BIDS dataset configuration
bids:
  validate_bids: true                # Enable BIDS validation
  bids_version: "1.8.0"             # BIDS specification version
  sessions: null                     # null = all sessions, or specify: ["baseline", "followup"]
  tasks: null                        # null = all tasks, or specify: ["rest", "task"]
  runs: null                         # null = all runs, or specify: ["1", "2"]
  dwi_suffixes: ["dwi"]             # DWI file suffixes to process
  phase_encoding_directions: ["AP", "PA", "LR", "RL"]  # Expected phase encoding directions
  required_dwi_files: ["dwi.nii.gz", "dwi.bval", "dwi.bvec"]  # Required DWI files
  optional_files: ["dwi.json", "T1w.nii.gz", "T2w.nii.gz"]    # Optional files

# Processing parameters - optimized for HPC
processing:
  # General processing - adjust based on your HPC allocation
  n_threads: 16                      # Number of CPU threads (adjust for your HPC node)
  force_overwrite: false             # Force overwrite existing outputs
  
  # Denoising parameters
  denoise_method: "dwidenoise"       # DWI denoising method (MRtrix3)
  
  # TopUp parameters
  topup_config: "b02b0.cnf"         # TopUp configuration file
  readout_time: null                 # Total readout time (auto-detect from JSON if None)
  
  # Eddy parameters
  eddy_cuda: false                   # Use CUDA acceleration (set to true if GPU available)
  eddy_method: "eddy"                # Use regular eddy for CPU-only HPC nodes
  bet_threshold: 0.2                 # BET threshold for brain extraction
  
  # Registration parameters
  registration_type: "SyNQuick"      # ANTs registration type
  
  # Tractography parameters
  n_tracks: 5000000                  # Number of tracks to generate per hemisphere
  track_algorithm: "iFOD2"           # Tracking algorithm (MRtrix3)
  track_cutoff: 0.045                # FOD amplitude cutoff for terminating tracks
  
  # SIFT2 parameters
  sift2_ndi_threshold: 0.1           # NDI threshold for SIFT2 processing mask
  sift2_output_coeffs: true          # Generate SIFT2 coefficients files
  sift2_output_mu: true              # Generate mu (proportionality coefficient) files
  sift2_fd_scale_gm: false           # Scale fibre density by GM volume (optional)

# ROI configuration
rois:
  roi_names:                         # List of ROIs in fsaverage space
    - "L_bnst_fsaverage"            # Left BNST
    - "R_bnst_fsaverage"            # Right BNST
    - "L_amygdala_fsaverage"        # Left amygdala
    - "R_amygdala_fsaverage"        # Right amygdala
    - "L_hippocampus_fsaverage"     # Left hippocampus
    - "R_hippocampus_fsaverage"     # Right hippocampus
    - "L_vmPFC_fsaverage"          # Left ventromedial prefrontal cortex
    - "R_vmPFC_fsaverage"          # Right ventromedial prefrontal cortex
    - "L_insula_fsaverage"         # Left insula
    - "R_insula_fsaverage"         # Right insula
    - "L_hypothalamus_fsaverage"   # Left hypothalamus
    - "R_hypothalamus_fsaverage"   # Right hypothalamus
  
  gmwm_boundary: true               # Use GM-WM boundary for tractography

# Complete pipeline steps (all steps included)
steps_to_run:
  - "copy_data"                      # Copy and organize BIDS data
  - "denoise"                        # DWI denoising using MP-PCA
  - "topup"                          # Field map estimation and correction
  - "eddy"                           # Eddy current and motion correction
  - "mdt"                            # Microstructure modeling (NODDI, DTI) - NOW INCLUDED
  - "mrtrix_prep"                    # MRtrix3 preprocessing (response, FOD)
  - "tractography"                   # Generate tracks per hemisphere
  - "sift2"                          # Track filtering and optimization
  - "roi_registration"               # ROI registration to subject space
  - "connectome"                     # Generate connectivity matrices

# Subject filtering (regex pattern)
subject_filter: null                 # null = all subjects, or specify pattern like "^(001|002)$" 